### ISSUE TITLE
[ENHANCEMENT] Rename cookies

### ISSUE THREAD

**Issue by tklein1801** [better-auth/better-auth#122]
As a developer, I would like to be able to determine what certain cookies are called or define a certain prefix to create certain semantics. Therefore, it would be great if I could define this in my better-auth instance

Like
```ts
export const auth = betterAuth({
  database: pool,
  advanced: {
    cookie: {
      crossSubDomainCookies: {
        enabled: true,
        domain: 'better-auth.com',
        eligibleCookies: [] // what do I even put here?
      },
      prefix: "DEFINE_YOUR_PREFIX_RIGHT_HERE"
    }
  },
});
```

**Comment by Bekacru** [comment]
I'm not sure if we should allow changing the cookie prefix. It adds unnecessary complexity since cookie names are just identifiers, and having the ability to easily identify if a cookie is from "better-auth" by its name is valuable to keep. 

However, for eligible cookies in cross-subdomain, we should have proper typed strings.

**Comment by tklein1801** [comment]
Okay, but atleast we got one todo
- [ ] Eligible cookies in cross-subdomain, should have proper typed strings.
