### ISSUE TITLE
Q: Why is it not Node-independent?

### ISSUE THREAD

**Issue by k-kozika** [better-auth/better-auth#150]
[Here](https://github.com/better-auth/better-auth/blob/dfbcbdf5acecee388c8cf60acdadf8228a0e91ad/packages/better-auth/src/crypto/password.ts#L1) is an import that uses `node:`
Why is Scrypt encryption possible using [`Oslo`](https://oslo.js.org/reference/password/Scrypt/) or [`@noble/hashes`](https://github.com/paulmillr/noble-hashes?tab=readme-ov-file#scrypt) but they are not used?

**Comment by Bekacru** [comment]
Our implementation is similar to Oslo's, which also uses "node:crypto." But, because Oslo uses classes, we ran into an issue where the `generateKey` method lost its reference after passing through our init context. Since "node:crypto" is already supported by multiple runtimes, we opted to continue using it rather than switching to `@noble/hashes`, even though noble doesn't rely on Node's implementation.

**Comment by k-kozika** [comment]
I see.
