### ISSUE TITLE
Need an option to require email verification before create session while in signup or login

### ISSUE THREAD

**Issue by qasimali09** [better-auth/better-auth#181]

**Comment by Bekacru** [comment]
You can do this using database hooks. Check if the user isn't verified and return false to not allow session creation.

https://www.better-auth.com/docs/concepts/database#database-hooks

**Comment by PawelPotempa** [comment]
Just to add onto that, as it's also a feature I'm interested in. Is that what you had in mind @Bekacru?

```
session: {
    create: {
      before: async (session) => {
          const user = await db.query.user.findFirst({
              where: (user, { eq }) => eq(user.id, session.userId)
          });
          if (!user?.emailVerified && user) {
              return false;
        }
     }
  }
},
```

If so - it does prevent session from being created, but at the same time it prevents the verification email from being sent.
`{message: "Failed to create session"}`

I've also tried sending the email manually instead, but got the exact same response. 
```
if (!user?.emailVerified && user) {
          await auth.api.sendVerificationEmail({
              body: {
                  email: user.email,
              },
          });
          return false;
      }
```

**Comment by Bekacru** [comment]
Good catch! For the next release, we should send the email verification before creating the session.

**Comment by PawelPotempa** [comment]
I saw that it has been fixed in the 0.4.12-beta.6, yet one issue still persists. The api still throws an error, despite successfully sending the verification email. I've tried catching it or throwing my own error instead of returning false, but with nothing major to show for it. Moreover, it seems counterintuitive for the API to return a 400 status code when the process appears to have executed correctly.

I think this might call for a more robust implementation, perhaps a config option to the betterAuth init function, such as `session: {requireEmailVerification:true}` would make sense?

**Comment by PawelPotempa** [comment]
I think this feature broke again with one of the releases. On @latest it seems to ignore the `requireEmailVerification: true` option - no type errors, but signing up with credentials does create a session again.

**Comment by Bekacru** [comment]
> I think this feature broke again with one of the releases. On @latest it seems to ignore the `requireEmailVerification: true` option - no type errors, but signing up with credentials does create a session again.

It seems like that was moved to `autoSignIn: false`, but `requireEmailVerification` should still enforce it as well. Will be corrected in the next release!

**Comment by platform-kit** [comment]
@Bekacru why are features being renamed? Is this project unstable?
