### ISSUE TITLE
missing adapter deps

### ISSUE THREAD

**Issue by luksch42** [better-auth/better-auth#45]
The prettier dependency is missing

https://github.com/better-auth/better-auth/blob/main/packages/better-auth/src/adapters/drizzle-adapter/index.ts

**Comment by luksch42** [comment]
same for mysql2, better-sqlite3, and pg to get it running

**Comment by Bekacru** [comment]
The latest release addresses the Prettier dependency. But we've removed database packages from our dependencies since Next.js requires external dependencies to be installed in the main project. It didn't make sense to show errors for better-sqlite3 if you weren't using it. Now, if the required database package is missing, you'll get an error prompting you to install them. Let me know if you still have an issue.

**Comment by luksch42** [comment]
I think that's fixed. Someone on discord had the same issue, which was fixed.
