### ISSUE TITLE
get-session endpoint returning 200 on error

### ISSUE THREAD

**Issue by awesomepandapig** [better-auth/better-auth#801]
Currently when querying `/api/auth/get-session` without a valid session token returns `null` with a `200` response status.

I believe that this endpoint should instead return a `400` error indicating that the request is missing a valid token, or a `401/403` if the token is malformed or not valid for the particular resource.

Without proper error codes validation is much more difficult.

**Comment by Bekacru** [comment]
We're returning `null` to stay consistent with `auth.api.getSession`. Users won’t expect this to throw an error since it's primarily used in middleware or other contexts where you need to check if a session exists. Plus, throwing an error would generate unnecessary logs if you're using monitoring services for expected behavior. On the client, you can check if `isPending` is `false` and `data` is still `null` to determine whether the session was found.

**Comment by awesomepandapig** [comment]
Hmmm... I see. I am using express as my backend so I was thinking more in terms of an explicit client-server model where the server would be passing explicit error messages to the client if the session is invalid or DNE. 

For now, though, data being null works great with my Next.JS middleware.
