### ISSUE TITLE
NextJS Pages Router API Route Doesn't work with Node Handler

### ISSUE THREAD

**Issue by daveycodez** [better-auth/better-auth#920]
### Is this suited for github?

- [X] Yes, this is suited for github

### To Reproduce

Error:  ⨯ TypeError: Response body object should not be disturbed or locked

/pages/api/auth/[...all]
```ts
import { NextApiRequest, NextApiResponse } from "next"
import { toNodeHandler } from "better-auth/node"
import { auth } from "@/lib/auth"

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
    await toNodeHandler(auth)(req, res)
}
```

When I convert it to an "edge" endpoint, I can get the NextRequest object and use the toNextJSHandler, but the Edge config doesn't support Crypto for JWT's and is broken there as stated from a previous issue.

For some of us.. the App Router is not great. Please consider adding documentation for Pages Router installation and Edge support

### Current vs. Expected behavior

Support for NextJS Pages Router

### What version of Better Auth are you using?

1.0.21

### Provide environment information

```bash
NextJS 15 Pages Router API Route
```

### Which area(s) are affected? (Select all that apply)

Backend

### Auth config (if applicable)

```typescript
import { betterAuth } from "better-auth"
import { jwt, bearer } from "better-auth/plugins"
import { NeonHTTPDialect } from "kysely-neon"

import { getURL } from "@/lib/utils"

export const auth = betterAuth({
    baseURL: getURL(),
    database: {
        dialect: new NeonHTTPDialect({
            connectionString: process.env.DATABASE_URL!,
        }),
        type: "postgres"
    },
    emailAndPassword: { enabled: true },
    plugins: [
        jwt(),
        bearer()
    ]
})
```

**Comment by KastanDay** [comment]
Hey @daveycodez Can you confirm that BetterAuth works for you in /pages router in the Node runtime and it only breaks when you convert it to Edge runtime? Are you able to authenticate pages running in /pages router?

**Comment by daveycodez** [comment]
@KastanDay 

It's the opposite actually. If I use edge runtime in the Pages API Route, everything works EXCEPT /api/auth/token which gives crypto errors, likely due to edge limitations which I hope we can resolve.

But for straight up Pages API Routes it's not working

```ts
import { NextApiRequest, NextApiResponse } from "next"
import { toNodeHandler } from "better-auth/node"
import { auth } from "@/lib/auth"

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
    await toNodeHandler(auth)(req, res)
}
```

Gives errors about locking the response body.

**Comment by KastanDay** [comment]
Very interesting, thank you for the details. 

I'm unable to get /pages router working at all. /app router works fine, but if I try to move any part of it into my existing /pages code base, I'm plagued by `ERR_REQUIRE_ESM` errors due to `require()` instead of `import {}`. 

Sad to see you also can't get any form of pages router working even though @Bekacru mentioned pages "should" be supported: https://github.com/better-auth/better-auth/issues/850

I'd love any advice possible to get /pages working - we have a legacy codebase.

**Comment by daveycodez** [comment]
Heheh I'm one of the special ones who still think the Pages router is superior. But I work with hybrid static export projects and App Router is not very compatible with that. But yes Pages router is still real, proper support and documentation would be great

**Comment by Bekacru** [comment]
```ts
export const config = {
	api: {
		bodyParser: false,
	},
};
```

hey @daveycodez  and @KastanDay I think if you prevent the api route from pre-parsing the body it should work as expected.

**Comment by daveycodez** [comment]
@Bekacru 

Yea bodyParser was the issue thanks! Although it would be great if we can get edge support working with JWT's sometime

**Comment by KastanDay** [comment]
I cannot thank you enough @Bekacru - that's phenomenal. I'm really impressed by this library and how you seem to be a CRACKED developer. Cheers!

**Comment by KastanDay** [comment]
@Bekacru I spoke too soon - I'm still facing an `ERR_REQUIRE_ESM` error from `nanostores`. 

I'm upgraded to `better-auth@1.1.1`.

```
Error: require() of ES Module /Users/kvday2/code/ai-ta/b/uiuc-chat-frontend/node_modules/nanostores/index.js from /Users/kvday2/code/ai-ta/b/uiuc-chat-frontend/node_modules/better-auth/dist/react.cjs not supported.
Instead change the require of index.js in /Users/kvday2/code/ai-ta/b/uiuc-chat-frontend/node_modules/better-auth/dist/react.cjs to a dynamic import() which is available in all CommonJS modules.
```

Here's our [fairly minimal code](https://github.com/CAII-NCSA/uiuc-chat-frontend/pull/225).

I first thought it worked because un-commenting it works. But a page refresh causes the `ESM` error. Here's 20 second video showing the behavior: 

![CleanShot 2024-12-21 at 11 42 25](https://github.com/user-attachments/assets/d5e6d658-d0c0-4418-8ecb-1186b71cff02)

This behavior is identical if I use /app router (with `toNextjsHandler`) and import that into pages, or keep everything in /pages (with `toNodeHandler`). 

Any advice greatly appreciated! Any luck @daveycodez ?
