### ISSUE TITLE
[webpack.cache.PackFileCacheStrategy] Serializing big strings (107kiB) warnings in Next.js

### ISSUE THREAD

**Issue by daveycodez** [better-auth/better-auth#982]
### Is this suited for github?

- [X] Yes, this is suited for github

### To Reproduce

Turn off --turbo in npm run dev

The console seems to be getting spammed with the following:

```shell
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (223kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (103kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (107kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
```

I'm not 100% sure where this is coming from but it is a minimal project with shadcn. I did however run @next/bundle-analyzer and better-auth is ticking in at around 949kb which is the largest module out of all of them. drizzle-orm is around 213kb, @neondatabase/serverless around 139kb

Maybe I could be wrong and better-auth isn't the culprit but from the bundle analyzer it is the largest atm

### Current vs. Expected behavior

No console warnings

### What version of Better Auth are you using?

1.0.22

### Provide environment information

```bash
Next.js Pages Router
```

### Which area(s) are affected? (Select all that apply)

Backend

**Comment by Bekacru** [comment]
Could you try adding this to your next config for your use case

```ts
experimental: {
  optimizePackageImports: ["better-auth"]
}
```

Regarding the bundle size:  
- First, this is server-side, so it shouldn't be a major concern. The client bundle should remain very small.  
- We ship Kysely with Better Auth, which accounts for at least a quarter of the bundle size.  
- To enable better tree-shaking, you can import plugins directly from their specific paths instead of `/plugins` like import jwt plugin from `/plugins/jwt` instead.
- Most of the size is cause we have everything in one package. We could split plugins, clients, and other components into separate packages to make it leaner. But, the convenience of having everything in a single package `better-auth` feels like a bigger win in many ways.

**Comment by daveycodez** [comment]
I tried both and I'm still seeing the warnings, I'll have to setup a barebones project to see if this occurs or maybe even it's shadcn or something else causing it. I'm mainly just trying to suppress the warnings for a cleaner dev console but can't seem to find a good method, Webpack config isn't working.

**Comment by daveycodez** [comment]
Adding this to next.config.json is suppressing it correctly. All the other warningsFilter options etc weren't working but I discovered this. I'm cool with them just being suppressed tbh, if anyone stumbles here from Google:

### Suppress [webpack.cache.PackFileCacheStrategy] Serializing big strings warnings in Next.js console
```ts  
webpack: (config) => {
    config.infrastructureLogging = { level: "error" }
    return config
  },
```
